version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    assignees:
      - 'Lalit2005'
    reviewers:
      - 'Lalit2005'
